### ISSUE TITLE
Are you aware of ResumableFunctions.jl?

### ISSUE THREAD

**Issue by xiaodaigh** [schlichtanders/Continuables.jl#4]
https://github.com/BenLauwens/ResumableFunctions.jl

Wonder if there is a pros and cons and compare and contrasts?

**Comment by schlichtanders** [comment]
Thanks for pointer! Indeed I am aware and already included a tiny comparison in the documentation
https://schlichtanders.github.io/Continuables.jl/dev/benchmark/#Related-packages

summary: different approach. ResumableFunctions still support `iterate` protocoll, `Continuables` do not and hence can lead to much faster performances.
