### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by detrin** [schlichtanders/Continuables.jl#6]
I have noticed your package and I think it is faster in my case then ResumableFunctions.jl. I currently added your package to dependencies of OpenQuantumSystems.jl, but I would like to make sure, that no unnecessary dependencies are left.

Looking at your Project.toml

```
name = "Continuables"
uuid = "79afa230-ca09-11e8-120b-5decf7bf5e25"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "1.0.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataTypesBasic = "83eed652-29e8-11e9-12da-a7c29d64ffc9"
ExprParsers = "c5caad1f-83bd-4ce8-ac8e-4b29921e994e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SimpleMatch = "a3ae8450-d22f-11e9-3fe0-77240e25996f"

[compat]
BenchmarkTools = "0.5"
Compat = "2.1, 3"
DataTypesBasic = "1.0"
ExprParsers = "1.0"
SimpleMatch = "1.0"
OrderedCollections = "1.3"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
```
It looks like BenchmarkTools.jl, OrderedCollections.jl, Compat.jl are just imported but not used in src folder. I would also suggest using [Inequality specifiers](https://pkgdocs.julialang.org/v1/compatibility/) for [compat] section if backward compatibility is really needed.

**Comment by detrin** [comment]
I now see that you have CompatHelper action set up, but it wasn't executed in the past 6 months. GitHub is now disabling Actions in inactive repos.

**Comment by detrin** [comment]
Due the inactivity in this repository BenchmarkTools is held back. Now I have package conflicts, which I have to solve manually. Please run CompatHelper on this repo.

↓ BenchmarkTools v0.7.0 ⇒ v0.5.0

**Comment by detrin** [comment]
So I checked the speed up achieved with your package in comparison with ResumableFunctions as follows
```julia
using OpenQuantumSystems
using BenchmarkTools, LinearAlgebra, Random 
using ResumableFunctions
using Continuables 

Random.seed!(0)

modes = [Mode(2., 2.)]
mols = [
    Molecule(modes, 5, [0., 200.]),
    Molecule(modes, 5, [0., 300.]),
    Molecule(modes, 5, [0., 200.])
    ]

agg = Aggregate(mols)
agg.coupling[2, 3] = 100
agg.coupling[3, 2] = 100

aggIndices = getIndices(agg; groundState=false)
base = GenericBasis([length(aggIndices)])
FCFact = getFranckCondonFactors(agg, aggIndices; groundState=false)
Ham = getAggHamiltonian(agg, aggIndices, FCFact; groundState=false)
base = GenericBasis([length(aggIndices)])
psi0 = randstate(base)
rho0 = dm(psi0)

evolutionOperatorIterator(Hamiltonian::Operator, tspan::Array) = @cont begin
    N = length(tspan)
    Ham_lambda, Ham_S = eigen(Hamiltonian.data)
    base = GenericBasis([size(Ham_lambda, 1)])
    Ham_Sinv = inv(Ham_S)
    
    U_diagonal = zero(Ham_lambda)
    U_diagonal = map(lambda -> exp(-1im * lambda * tspan[1]), Ham_lambda)
    U = Ham_S * diagm(U_diagonal) * inv(Ham_S)
    U_op = DenseOperator(base, base, U)
    cont(U_op) 

    for t_i in 2:N
        U_diagonal .= map(lambda -> exp(-1im * lambda * tspan[t_i]), Ham_lambda)
        U_op.data .= Ham_S * diagm(U_diagonal) * inv(Ham_S)
        cont(U_op) 
    end
end

@resumable function evolutionOperatorIterator2(Hamiltonian::Operator, tspan::Array)
    N = length(tspan)
    Ham_lambda, Ham_S = eigen(Hamiltonian.data)
    base = GenericBasis([size(Ham_lambda, 1)])
    Ham_Sinv = inv(Ham_S)
    
    U_diagonal = zero(Ham_lambda)
    U_diagonal = map(lambda -> exp(-1im * lambda * tspan[1]), Ham_lambda)
    U = Ham_S * diagm(U_diagonal) * inv(Ham_S)
    U_op = DenseOperator(base, base, U)
    @yield U_op

    for t_i in 2:N
        U_diagonal .= map(lambda -> exp(-1im * lambda * tspan[t_i]), Ham_lambda)
        U_op.data .= Ham_S * diagm(U_diagonal) * inv(Ham_S)
        @yield U_op 
    end
end
```

Continuables:
```julia
tspan = [0.0:0.1:1.0;]
@btime let
    foreach(evolutionOperatorIterator(Ham, tspan)) do U_op
    end
    print(".")
end
```
................................................  222.921 ms (196 allocations: 112.95 MiB)
ResumableFunctions:
```julia
tspan = [0.0:0.1:1.0;]
@btime let
    for U_op in evolutionOperatorIterator2(Ham, tspan)
    end
    print(".")
end
```
............................................  198.945 ms (16780 allocations: 113.39 MiB)

My highest concern is the speed and in this example we can see reasonable size of systems, that will be studied. With your package there is 12% speed up, so I am switching to ResumableFunctions in OpenQuantumSystems for now. Let me know when you have enough time to solve the issue.

**Comment by schlichtanders** [comment]
@detrin I am very sorry for reacting that slowly. I am definitely motivated to fix these issues and also I have time the next month.
Will come back to you before Juliacon.
Thank you very much for pointing out these issues

**Comment by schlichtanders** [comment]
@detrin Compat entries are now updated. Thank you again for your help.

I hope everything works for you now
